name: Build and Deploy to GKE

on:
  push:
    branches: [ "gke" ]

env:
  PROJECT_ID: YOUR_PROJECT_ID # TODO: update Google Cloud project id
  GAR_LOCATION: YOUR_GAR_LOCATION # TODO: update Artifact Registry location
  SERVICE: YOUR_SERVICE_NAME # TODO: update Cloud Run service name
  REGION: YOUR_SERVICE_REGION # TODO: update Cloud Run service region
  GAR_NAME: YOUR_GAR_REPO_NAME

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          #credentials_json: ${{ secrets.GCP_CREDENTIALS }}
          workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
          service_account: ${{ secrets.WIF_SERVICE_ACCOUNT}} 
      - name: deploy to gke
        run: |
          gcloud container clusters get-credentials my-auto-cluster --region us-east1
          kubectl apply -f gke-resources.yaml