name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies and run the application
        run: |
           go mod init github.com/ilangodhandapani/go
           go mod tidy
           go get -u github.com/gin-gonic/gin
           go run main.go
      - name: Test application
        run: |
          curl "http://localhost/"
