name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build and run container
        run: |
          docker build -t my-golang-app .
          docker run -it --rm -d -p 8080:8080 --name web my-golang-app
      - name: Test container
        run: |
          docker exec web curl "http://localhost:8080"
           

